### PR TITLE
create file and add content

### PR DESCRIPTION
**Pull request by Namithesh**
created file and added content.

### CODE REVIEW

**Review by anurag629 — CHANGES_REQUESTED** [review]
@HyperNB  You have to search the question from leetcode and paste it from there.
Those two pictures I attached are for example so you can edit the readme file accordingly.

Do not copy from pictures................

**Comment by anurag629** [comment]
@HyperNB  make all files inside your branch whichever you have created.

**Comment by Namithesh** [comment]
sorry my bad. i apologize

**Comment by anurag629** [comment]
> sorry my bad. i apologize

Don't worry make changes and commit and push those changes

**Comment by anurag629** [comment]
@HyperNB If have any problem/doubt then you can ask me.

**Comment by anurag629** [comment]
@HyperNB are you working on it??

**Pull request closed without merging**
